name: CI Simple
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v3
      - name: Ejecutar script
        run: echo '¡Hola desde GitHub Actions!'
      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Ejecutar script Python
        run: python script.py